config/routes.rb
Rails.application.routes.draw do
  get 'tag_users/create'
  get 'tag_users/destroy'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: "static_pages#home"
  resources :users, only: [:show]
  resources :messages, only: [:index, :show, :new, :create]
  resources :chats, only: [:index, :show, :new, :create]
  resources :tags
  resources :tag_users, only: [:create, :destroy]
  resources :posts
  resources :groups do
    member do
      get :members
      get :requests
      get :invite
    end
  end
  resources :group_users, only: [:create, :destroy, :update]
  resources :ads do
    member do
      patch :archive
      patch :unarchive
      get   :messages
    end
  end
  resources :categories

  mount ActionCable.server, at: '/cable'
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :from, class_name: "User"
  belongs_to :chat, touch: true

  validates :text, presence: true, length: {maximum: 500} 
  validates :from, presence: true
  validates :ad_id, presence: false
  
  def to_param
    from.name
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  include ParamsHelper
  include ChatHelper

  before_action :authenticate_user!

  def show
    message = Message.find(params[:id])
    chat = Chat.find(message.chat_id)
    cu = ChatUser.find_by(user_id: current_user.id, chat_id: chat.id)
    @last_read = cu.last_read
    render :partial => 'message', locals: { message: message }
  end

  def create
    # If no chat id, see if we need a new chat
    if message_params[:chat_id].empty?
      users = helpers.parse_participants(message_params[:participants])
      if Chat.with_users(users)
        chat = Chat.with_users(users)
      else
        chat = Chat.new(subject: nil)
        chat.users = users
        chat.save
      end
    else
      chat = Chat.find(message_params[:chat_id])
    end

    @message = chat.messages.build(
      from: current_user,
      text: message_params[:text],
      ad_id: message_params[:ad_id] ? message_params[:ad_id] : nil
    )

    if @message.save && message_params[:ad_id]
      redirect_to chat_path(chat)
      return
    end
    
    if @message.save!
      cu = ChatUser.find_by(user_id: current_user.id, chat_id: chat.id)
      @last_read = cu.last_read
      cu.touch(:last_read)
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.append(:messages, partial: "messages/message",
            locals: {message: @message})
        end
        format.html do
          render :layout => false, :partial => 'messages/message', :locals => { message: @message }
        end
      end
      
      chat.users.each do |u|
        ActionCable.server.broadcast(
          "messages_channel_#{u.username}",
          { type: 'message', message: @message} )
        ActionCable.server.broadcast(
          "messages_channel_#{u.username}",
          { type: 'unread_chats', unread_chats: u.unread_chats} )
      end
    else
      flash[:alert] = "Couldn't post your message"
      redirect_to chat_path(chat)
    end
  end

  private
    def message_params
      params.require(:message).permit(:text, :to_id, :chat_id, :participants, :ad_id)
      # participants is only used if creating a chat (e.g. from ad)
      # ad_id only used from an ad
    end
end

app/views/messages/_form.html.erb
<%= form_with(model: @message) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :text, class: 'header' %>
    <%= f.text_area :text %>

    <%= f.label :to, class: 'header' %>
    <%= f.collection_select :to_id, User.all, :id, :username %>

    <%= f.submit yield(:button_text) %>
<% end %>

app/views/messages/_message.html.erb
<li id="message-id-<%= message.id %>"
    class="message<%= @last_read < message.created_at ? ' unread' : ''%>"
    <% if message.from_id == current_user.id %>
        data-from="self"
    <% else %>
        data-from="<%= message.from_id %>"
    <% end %>
    >
    <% if message.ad_id && ad = Ad.find(message.ad_id) %>
        <span class="ad">
            <%= link_to ad, target: "_top" do %>
                This message is in response to <%= ad.title %>.
            <% end %>
        </span>
    <% end %>
    <span class="text"><%= message.text %></span>
    <span class="time"><%= time_ago_in_words(message.created_at) %> ago.</span>

</li>

app/views/messages/index.html.erb
<% provide(:title, "Messages") %>
<h2>Messages</h2>

<%= link_to 'Post a new message', new_message_path %>

<% @users.each do |c| %>
    <ol class="conversations">
        <li><%= link_to c.username, message_path(c.username) %></li>
    </ol>
<% end %>

app/views/messages/show.html.erb
<<% provide(:title, "Conversation with " + @user.username) %>>

<h2><%= @user.username %></h2>

<ol id="messages">
    <%= render @messages %>
</ol>

<%= form_with(model: @message) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.text_area :text %>

    <%= f.hidden_field :to_id, value: @user.id %>
    <%= f.hidden_field :ad_id %>

    <%= f.submit "Send" %>
<% end %>