config/routes.rb
Rails.application.routes.draw do
  get 'tag_users/create'
  get 'tag_users/destroy'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: "static_pages#home"
  resources :users, only: [:show]
  resources :messages, only: [:index, :show, :new, :create]
  resources :chats, only: [:index, :show, :new, :create]
  resources :tags
  resources :tag_users, only: [:create, :destroy]
  resources :posts
  resources :groups do
    member do
      get :members
      get :requests
      get :invite
    end
  end
  resources :group_users, only: [:create, :destroy, :update]
  resources :ads do
    member do
      patch :archive
      patch :unarchive
      get   :messages
    end
  end
  resources :categories

  mount ActionCable.server, at: '/cable'
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :group_users, dependent: :destroy
  has_many :members, :through => :group_users, :source => :user
  has_many :posts, as: :subject

  enum privacy: { open: 'open', request: 'request', invite: 'invite' }
  validates :privacy, inclusion: { in: privacies.keys}

  validates :name, presence: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: [:show, :edit, :update, :destroy, :members, :requests, :invite]
  before_action :group_owner, only: [:edit, :update, :destroy, :requests]

  def index
    # need different page params for different sections
    @groups = Group.all.paginate(page: params[:page])
    @ownedgroups = current_user.groups.paginate(page: params[:page])
    @memberships = current_user.memberships.paginate(page: params[:page])
  end

  def show
    if @group.members.include? current_user
      @groupuser = GroupUser.where(user_id: current_user.id, group_id: @group.id).first
    else 
      @groupuser = GroupUser.new
    end
    @post = Post.new
    @posts = @group.posts.order("created_at DESC").paginate(page: params[:page])

    unless @groupchat = Chat.with_users(@group.members)
      @groupchat = Chat.new(subject: @group, users: @group.members)
    end
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.build(group_params)
    if @group.save
        flash[:success] = "Group created!"
        redirect_to @group
    else
        render 'new'
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
        flash[:success] = "Group updated"
        redirect_to @group
    else
        render 'edit'
    end
  end

  def destroy
    @group.destroy
    flash[:success] = "Group deleted"
    redirect_to groups_url
  end

  def members
    @members = @group.group_users.where("confirmed = true")
      .paginate(page: params[:page])
  end

  def requests
    if @group.privacy == 'request'
      @members = @group.group_users.where("confirmed = false")
        .paginate(page: params[:page])
      render 'members'
    else
      redirect_to @group
    end
  end

  def invite
    # todo filter/search users
    @users = User.where.not(id: GroupUser.where(group_id: @group.id).pluck(:user_id))
    @users = @users.paginate(page: params[:page])
    @gu = GroupUser.new
  end

  private
  def group_params
      params.require(:group).permit(:name, :privacy)
  end

  def set_group
    @group = Group.find(params[:id])
  end

  def group_owner
    if current_user != @group.user
      head :unauthorized
    end
  end
end

app/views/groups/_form.html.erb
<%= form_with(model: @group, local: true) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.label :name, class: 'header' %>
    <%= f.text_field :name %>
    <%= f.select :privacy, Group.privacies.keys.map { |w| [w.humanize, w] } %>

    <%= f.submit yield(:button_text) %>
<% end %>

app/views/groups/_group.html.erb
<li id="group-id-<%= group.id %>">
    <h4 class="group-name"><%= link_to group.name, group_path(group.id) %></h4>
</li>

app/views/groups/_member_view.html.erb
<ul>
    <li><%= link_to 'Members', members_group_path(@group) %></li>
    <li><%= link_to 'Invite new members', invite_group_path(@group) %></li>
    <li></li>
</ul>

<h3>Make a post</h3>
<%= turbo_frame_tag("posts") do %>
    <%= render :partial => 'posts/form', :locals => { subject: group, post: post } %>

    <%= render :partial => 'groups/posts', :locals => {posts: posts }%>
<% end %>

app/views/groups/_non_member_view.html.erb
<turbo-frame id="join-group">
    <% if group.user == current_user%>
        <p>You own this group.</p>
    <% elsif group.members.include?(current_user) &&
        group.group_users.find_by(user_id: current_user.id).confirmed == false %>
        <% case group.privacy
           when 'request' %>
            <p>You have requested to join this group.</p>
        <% when 'invite' %>
            <p>You are invited to join this group.</p>
            <%= form_with(model: groupuser) do |f| %>
                <%= render 'shared/error_messages', object: f.object %>
                <%= f.hidden_field :confirmed, value: true %>
                <%= f.submit "Accept invitation" %>
            <% end %>
        <% end %>
    <% elsif group.members.include?(current_user) %>
        <% message = "Are you sure you want to leave "+ group.name + "?" %>
        <%= link_to "Leave group",
            groupuser,
            method: :delete,
            data: { confirm: message } %>
    <% elsif !group.members.include?(current_user) %>
        <% case group.privacy
           when 'open' %>
            <% button_text = 'Join ' + group.name %>
        <% when 'request' %>
            <% button_text = 'Request to join ' + group.name %>
        <% end %>
        <% unless group.privacy == 'invite' %>
            <%= form_with(model: groupuser, id: "joinForm") do |f| %>
                <%= render 'shared/error_messages', object: f.object %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.hidden_field :group_id, value: group.id %>
                <%= f.submit button_text %>
            <% end %>
        <% end %>
    <% end %>
</turbo-frame>

app/views/groups/_posts.html.erb
<h3>Posts</h3>
<% if posts.any? %>
    <ol id="group_posts">
        <%= render posts %>
    </ol>
    <%= will_paginate posts %>
<% else %>
    <p id="group_posts">No posts in this group yet!</p>
<% end %>

app/views/groups/edit.html.erb
<% provide(:title, "Edit " + @group.name) %>
<% provide(:button_text, "Edit") %>

<h2>Edit <%= @group.name %></h2>

<%= render 'form' %>

<%= link_to "delete", @group, method: :delete, data: {confirm: "Are you sure?" } %>

app/views/groups/index.html.erb
<% provide(:title, "Groups") %>
<h2>Groups</h2>

<%= link_to 'Create a new group', new_group_path %>

<h3>Groups you run</h3>
<% if @ownedgroups.any? %>
    <ol class="groups">
        <%= render @ownedgroups %>
    </ol>
    <%= will_paginate @ownedgroups %>
<% end %>

<h3>Groups you're a member of</h3>
<% if @memberships.any? %>
    <ol class="groups">
        <%= render @memberships %>
    </ol>
    <%= will_paginate @memberships %>
<% end %>

<h3>More groups</h3>
<% if @groups.any? %>
    <ol class="groups">
        <%= render @groups %>
    </ol>
    <%= will_paginate @groups %>
<% end %>

app/views/groups/invite.html.erb
<% provide(:title, @group.name + " invitations") %>
<h1><%= link_to @group.name, @group %></h1>
<h2>Invite new members</h2>
<% if @users.any? %>
    <ol class="users">
        <% @users.each do |u| %>
        <turbo-frame id="user-<%= u.id %>">
            <div>
            <%= render partial: 'users/user', locals: { user: u } %>
            <%= form_with(model: @gu) do |f| %>
                <%= render 'shared/error_messages', object: f.object %>
                <%= f.hidden_field :user_id, value: u.id %>
                <%= f.hidden_field :group_id, value: @group.id %>
                <%= f.hidden_field :confirmed, value: false %>
                <%= f.submit "Invite" %>
            <% end %>
            </div>
        </turbo-frame>
        <% end %>
    </ol>
    <%= will_paginate @users %>
<% end %>

app/views/groups/members.html.erb
<% provide(:title, @group.name + " members") %>
<h1><%= @group.name %> members</h1>

<% if @group.user == current_user %>
    <%= link_to 'Confirmed members',
        members_group_path %> |
    <%= link_to 'Membership requests', 
        requests_group_path %>
<% end %>
<% if @members.any? %>
    <ol class="groups">
        <%= render @members %>
    </ol>
    <%= will_paginate @members %>
<% end %>

app/views/groups/new.html.erb
<% provide(:title, "New group") %>
<% provide(:button_text, "Create") %>

<h1>Create a new group</h1>

<%= render 'form' %>

app/views/groups/show.html.erb
<% provide(:title, @group.name) %>
<h2 class="group-name"><%= @group.name %></h2>

<% if @group.user == current_user %>
    <h4>You own this group.</h4>
    <%= link_to 'Edit group', edit_group_path(@group) %>
<% else %>
    <h4>Owned by <%= link_to @group.user.username, user_path(@group.user) %>.</h4>
<% end %>

<% if @group.members.include? current_user %>
    <%= render :partial => 'groups/member_view', 
        :locals => { group: @group, post: @post, posts: @posts }  %>
<% else %>
    <%= render :partial => 'groups/non_member_view', 
        :locals => { group: @group, posts: @posts, groupuser: @groupuser }  %>
<% end %>