config/routes.rb
Rails.application.routes.draw do
  get 'tag_users/create'
  get 'tag_users/destroy'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: "static_pages#home"
  resources :users, only: [:show]
  resources :messages, only: [:index, :show, :new, :create]
  resources :chats, only: [:index, :show, :new, :create]
  resources :tags
  resources :tag_users, only: [:create, :destroy]
  resources :posts
  resources :groups do
    member do
      get :members
      get :requests
      get :invite
    end
  end
  resources :group_users, only: [:create, :destroy, :update]
  resources :ads do
    member do
      patch :archive
      patch :unarchive
      get   :messages
    end
  end
  resources :categories

  mount ActionCable.server, at: '/cable'
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :subject, polymorphic: true, optional: true
  has_many :messages, dependent: :destroy
  accepts_nested_attributes_for :messages
  has_many :chat_users, dependent: :destroy
  has_many :users, :through => :chat_users

  def unread_messages(user)
    cu = chat_users.find_by(user_id: user.id)
    messages.where("created_at > ?",  cu.last_read).count
  end

  def self.with_users(users)
    Chat.joins(:users)
        .where(users: { id: users })
        .group(:id)
        .having(User.arel_table[Arel.star].count.eq(users.length))
        .first
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  include ParamsHelper
  
  before_action :authenticate_user!

  def index
    @chats = current_user.chats.order("updated_at DESC")
    @chat_users = ChatUser.where(user_id: current_user.id)
    render :layout => false
  end

  def show
    if @chat = current_user.chats.find(params[:id])
      @users = @chat.users.where.not(id: current_user.id)
    end
    @newmessage = Message.new

    cu = ChatUser.find_by(user_id: current_user.id, chat_id: @chat.id)
    @last_read = cu.last_read
    cu.touch(:last_read)
    ActionCable.server.broadcast(
      "messages_channel_#{current_user.username}",
      { type: 'unread_chats', unread_chats: current_user.unread_chats} )
    render :layout => false
  end

  def create
    users = helpers.parse_participants(chat_params[:participants])

    if Chat.with_users(users)
      redirect_to chat_path(Chat.with_users(users))
    else
      chat = Chat.new(subject: chat_params[:subject])
      chat.users = users
      if chat.save
        redirect_to chat_path(chat)
      else
        flash[:alert] = "Couldn't start a new chat"
        redirect_to root_path
      end
    end
  end

  private
    def chat_params 
      params.require(:chat).permit(:subject_type, :subject_id, :participants)
    end

end

app/helpers/chat_helper.rb
module ChatHelper
    def other_users(chat)
        chat.users.where.not(id: current_user.id)
    end
end

app/views/chats/_chat.html.erb
<% if @chat_users.find_by(chat_id: chat.id).last_read < chat.updated_at %>
    <% new_messages = true %>
<% end %>
<li id="chat-id-<%= chat.id %>" class="chat<%= new_messages ? ' unread' : ''%>">
    <%= link_to chat_path(chat) do %>
        <% other_users(chat).each do |u| %>
            <%= render u %>
        <% end %>
    <% end %>
    <span id="unread-chat-<%= chat.id %>">
        <%= new_messages ? chat.unread_messages(current_user) : '' %>
    </span>
    <span class="time">Last message was <%= time_ago_in_words(chat.updated_at) %> ago.</span>
</li>

app/views/chats/index.html.erb
<turbo-frame id="messagesFrame">
    <div id="chatHeader">
        <h2>Messages</h2>
        <span id="chatClose" onclick="document.getElementById('messagesFrame').style.display = 'none';">-</span>
    </div>
    <ol id="chats">
        <%= render @chats %>
    </ol>

</turbo-frame>

app/views/chats/show.html.erb
<turbo-frame id="messagesFrame">
    <div id="chat-<%= @chat.id %>" data-controller="chat">    
        <div id="chatHeader">
            <%= link_to '←', chats_path %>
            <% @users.each do |u| %>
                <%= link_to u.username, user_path(u.username), target: "_top" %>
            <% end %>
        <span id="chatClose" onclick="document.getElementById('messagesFrame').style.display = 'none';">-</span>
        </div>
        <ol id="messages">
            <li></li>
            <% last_user = nil %>
            <%= render @chat.messages %>
        </ol>
        <%= form_with(model: @newmessage, id: "chatForm") do |f| %>
            <%= render 'shared/error_messages', object: f.object %>

            <%= f.text_area :text %>

            <%= f.hidden_field :chat_id, value: @chat.id %>

            <%= f.submit "Send", data: {action: "click->chat#send"} %>
        <% end %>
    </div>
</turbo-frame>