config/routes.rb
Rails.application.routes.draw do
  get 'tag_users/create'
  get 'tag_users/destroy'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: "static_pages#home"
  resources :users, only: [:show]
  resources :messages, only: [:index, :show, :new, :create]
  resources :chats, only: [:index, :show, :new, :create]
  resources :tags
  resources :tag_users, only: [:create, :destroy]
  resources :posts
  resources :groups do
    member do
      get :members
      get :requests
      get :invite
    end
  end
  resources :group_users, only: [:create, :destroy, :update]
  resources :ads do
    member do
      patch :archive
      patch :unarchive
      get   :messages
    end
  end
  resources :categories

  mount ActionCable.server, at: '/cable'
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name,
    presence: true,
    length: { maximum: 15 }
    # need to check for allowed chars here too
  
  validates :description,
    length: { maximum: 1000 }

  has_many :adtags, class_name: "AdTag", foreign_key: "tag_id"
  has_many :ads, through: :adtags, :source => :ad

  has_many :tagusers, class_name: "TagUser", foreign_key: "tag_id", dependent: :destroy
  has_many :followers, :through => :tagusers, :source => :user
  
  def to_param
    name
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  def show
    @ads = @tag.ads.active.paginate(page: params[:page])

    if @tag.followers.include? current_user
      @taguser = TagUser.find_by(user: current_user, tag: @tag)
    else
      @taguser = TagUser.new
    end
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to @tag
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @tag.update(tag_params)
      redirect_to @tag
    else
      render 'edit'
    end
  end

  def destroy
    @tag.destroy
    redirect_to tags_path
  end


	private
    def tag_params
      params.require(:tag).permit(:name, :description)
    end

    def set_tag
      @tag = Tag.find_by(name: params[:id])
    end
end

app/views/tags/_form.html.erb
<%= form_with(model: @tag) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.submit  yield(:button_text) %>

<% end %>

app/views/tags/_tag.html.erb
<dt><%= link_to tag.name, tag %></dt>
<dd>
    <%= tag.description %>
</dd>

app/views/tags/edit.html.erb
<% provide(:title, 'Edit a tag') %>
<% provide(:button_text, 'Edit tag') %>
<h1>Edit '<%= @tag.name %>' tag</h1>

<%= render 'form' %>

app/views/tags/new.html.erb
<% provide(:title, 'Create a new tag') %>
<% provide(:button_text, 'Create tag') %>
<h1>Create a new tag</h1>

<%= render 'form' %>

app/views/tags/show.html.erb
<% provide(:title, @tag.name) %>

<h1><%= @tag.name %></h1>

<%= link_to 'Edit', edit_tag_path(@tag) %>

<%=link_to "Delete", tag_path(@tag), :method => :delete %>  

<% if @taguser.user.present? %>
    <turbo-frame id="follow-tag">
    <%= link_to "Stop following", @taguser,
        method: :delete, data: {confirm: "Are you sure?" } %>
    </turbo-frame>
<% else %>
    <turbo-frame id="follow-tag">
    <%= form_with(model: @taguser, id: "followForm") do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <%= f.hidden_field :tag_id, value: @tag.id %>
        <%= f.submit "Follow" %>
    <% end %>
    </turbo-frame>
<% end %>

<p><%= @tag.description %></p>

<% if @tag.ads.any? %>
    <h2>Ads</h2>
    <ol class="ads">
        <%= render @ads %>
    </ol>
    <%= will_paginate @ads %>
<% end %>